### ISSUE TITLE
HELLO

### ISSUE THREAD

**Issue by huanmingcn** [edTheGuy00/android_device_zuk_z2pro#1]
HELLO, DOES THE DEVICE,  VENDOR AND THE KERNEL WORK?  HAVE YOU EVER COMPILE A LINEAGE ROM FOR ZUK Z2 PRO?

**Comment by huanmingcn** [comment]
I am sorry to tell that the device ,kernel and vendor couldn't make, when i input make, the device or kernel need something.  Aren't you online?

**Comment by huanmingcn** [comment]
missing "you"

**Comment by edTheGuy00** [comment]
I believe so of the Qualcomm blobs are missing, they were originally in the LibeageOS repo but got removed, you have to add the manually, 

https://emmaus.pro:3000/emmaus/android_device_qcom_common

There is also this repo we were working on, the rom works but it's buggy, I haven't had much time to work on it. 

https://emmaus.pro:3000/emmaus
https://emmaus.pro:3000/edTheGuy

**Comment by huanmingcn** [comment]
Oh, s**t! i just want to build a rom.

**Comment by edTheGuy00** [comment]
Maybe you can ask him for the source code, his rom works 100%. Let me know if you can get it :) http://bbs.lenovomobile.cn/z2pro/t780725/

**Comment by huanmingcn** [comment]
你是中国人？

**Comment by edTheGuy00** [comment]
I don't know Chinese

**Comment by huanmingcn** [comment]
Ok, i would try my best to ask him for that, if i got it, i will tell you.

**Comment by huanmingcn** [comment]
I asked him just now, and he reply 'O', i don't know the what the mean of it, but just now he replied he didn't want to public it. i am sorry

**Comment by hyman-lee** [comment]
I have sync the code you give me and Lineage, I succeed in compiling that. it worked, but the camera and the wired adb does not work, so i got the logcat by using LAN debug, I will fix it if I have time and I have power to fix it, thanks for your code.

**Comment by huanmingcn** [comment]
I have sync the code you give me and Lineage, I succeed in compiling that. It worked, but the camera and the wired adb didn't work, so I got the logcat by using LAN debug, I will fix it if I have time and I have power. Thanks for your giving me codes.
